name: Class-Inspector
version: 1.11
abstract: Get information about a class and its structure
author: Adam Kennedy <cpan@ali.as>
license: unknown
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.005
  File::Spec: 0.80
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
